### ISSUE TITLE
Spotify commands not working

### ISSUE THREAD

**Issue by pevecyan** [mkloubert/vs-media-player#2]
Nice extensions, but some commands for spotify does not work (next,previous track) even with web-api connection

**Comment by mkloubert** [comment]
@pevecyan 

Thanks, but could not reproduce the issue. For me anything works fine.

Can you post an exact workflow about the things you did?

Does the debug output (`CTRL + SHIFT + Y`) tell you something what is useful?

**Comment by pevecyan** [comment]
I followed your instructions step by step.
Could be a problem that I am using LocalTunnel for redirect URL?

This is what I get in Developer tools console:
`[Extension Host] [vs-media-player :: 2017-10-14 11:59:44] => [ERROR] StatusBarController(toggleMute): Unexpected status code: 403`

And this is my config:
`{
    "media.player": {
        "players": [
            {
                "name": "My Spotify player",
                "type": "spotify",

                "clientID": "myClientIdFromSpotify",
                "clientSecret": "mySecretFromSpotify",
                "redirectURL": "http://kakec.broz.ga"
            }
        ]
    }
}`

If you need anything else I am happy to help

**Comment by mkloubert** [comment]
@pevecyan 

Have you got a premium account?

Maybe that might be the problem, s. [Set Volume For User’s Playback / Response Format](https://developer.spotify.com/web-api/set-volume-for-users-playback/)

**Comment by pevecyan** [comment]
Oh snap, that explains everything, thanks for help :)

**Comment by pevecyan** [comment]
On the other hand, I extended your code little bit with robotjs, so now user can enable media keys for controlling Spotify music on windows 10. 
You can check commit [here ](https://github.com/pevecyan/vs-media-player/tree/windows-media)

**Comment by mkloubert** [comment]
Fantastic! :D

This will be a great feature ... I will take look on it!

**Comment by mkloubert** [comment]
@pevecyan 

What requirements do I need to use it?

When I try to import the module, I get the error `%1 ist keine zulässige Win32-Anwendung.` (something like `%1 is no valid Win32 application`).

```typescript
let robot: any;
try {
    robot = require('robotjs');
}
catch (e) {
    // throws an error on my machine
}
```

I am currently running VSCode 1.18.0-insider (x64).

**Comment by pevecyan** [comment]
Try to rebuild the package for the electron with https://github.com/octalmage/robotjs/wiki/Electron, be careful with electron version, latest stable VSCode use 1.7.7
