### ISSUE TITLE
Failed to connect to spotify

### ISSUE THREAD

**Issue by NightmareInfinity** [mkloubert/vs-media-player#4]
The extension seems to be using an outdated version of spotilocal which is causing it to stop checking at port 4380 when it should be checking up to 4389 in the latest version of spotilocal.
My spotify uses the port 4381 therefor this extension does not work.

**Comment by mkloubert** [comment]
@NightmareInfinity 

Thank you very much for the hint!

**I released version 3.0.0 of the extension with the latest version (0.4.4) of [spotilocal](https://www.npmjs.com/package/spotilocal).**
